### ISSUE TITLE
Cannot move when North/South wall is on players right or East/West is on the left

### ISSUE THREAD

**Issue by RobertDIV** [EmperorJack/Lunarcy-Repo#1]
This shows the directions you can/can't move in, unsure as to why
![gameerror](https://cloud.githubusercontent.com/assets/14267447/10156571/2fbc1f54-66df-11e5-9646-fb443e61c80e.png)

**Comment by RobertDIversen** [comment]
Problem was that GameState was using x,y and the other classes using it were y,x. Changed GameState to use y,x
